const MenuData = [
  {
    id: 1,
    image: 'Images/maggi.jpg',
    name: 'Maggi',
    category: 'Snacks',
    description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quia, dolor.',
    price: 20,
  },
  {
    id: 2,
    image: 'Images/chole.jpg',
    name: 'Chole Bhature',
    category: 'Snacks',
    description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quia, dolor.',
    price: 45,
  },
  {
    id: 3,
    image: 'Images/kachauri.jpg',
    name: 'Kachauri',
    category: 'Snacks',
    description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quia, dolor.',
    price: 25,
  },
  {
    id: 4,
    image: 'Images/south.webp',
    name: 'South Indian Food',
    category: 'Lunch',
    description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quia, dolor.',
    price: 65,
  },
  {
    id: 5,
    image: 'Images/thaali.webp',
    name: 'Thaali',
    category: 'Dinner',
    description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quia, dolor.',
    price: 65,
  },
  {
    id: 6,
    image: 'Images/vada.jpg',
    name: 'Vada-Paw',
    category: 'Snacks',
    description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quia, dolor.',
    price: 20,
  },
  {
    id: 7,
    image: 'Images/panpuri.webp',
    name: 'Pani-Puri',
    category: 'Snacks',
    description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quia, dolor.',
    price: 25,
  },
  {
    id: 8,
    image: 'Images/biryani.jpg',
    name: 'Biryani',
    category: 'Lunch',
    description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quia, dolor.',
    price: 85,
  },
  {
    id: 9,
    image: 'Images/chawal.jpg',
    name: 'Chawal-Daal',
    category: 'Lunch',
    description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quia, dolor.',
    price: 55,
  },
  {
    id: 10,
    image: 'Images/samosa.jfif',
    name: 'Samosa',
    category: 'Snacks',
    description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quia, dolor.',
    price: 25,
  },
  {
    id: 11,
    image: 'Images/momo.jpg',
    name: 'Momo',
    category: 'Snacks',
    description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quia, dolor.',
    price: 25,
  },
];

export default MenuData;
